### ISSUE TITLE
bad handshake

### ISSUE THREAD

**Issue by babakazizigithub** [TheErf23/Chisel-Xray-Tunnel#1]
درود مهندس
بنده طبق آموزش اجرا کردم .. روی سرور خارج اوکی هست ولی روی سرور ایران این ارور رو میده 

![Annotation 2](https://github.com/The-Erf/Chisel-Xray-Tunnel/assets/123808909/42635bf0-c968-4d6f-a997-57f3782e4348)

یه سوال داشتم؟ دامینی که توی هر دوتا سرور باید توی دستورات سرویس قرار بگیره باید همون دامینی باشه که پشت پروکسی کلودفلره دیگه؟ یا دامین سرور ایران باید فرق کنه؟

سپاس

**Comment by Erfan-Fazeli** [comment]
> درود مهندس بنده طبق آموزش اجرا کردم .. روی سرور خارج اوکی هست ولی روی سرور ایران این ارور رو میده
> 
> ![Annotation 2](https://private-user-images.githubusercontent.com/123808909/291016210-42635bf0-c968-4d6f-a997-57f3782e4348.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjI1ODYsIm5iZiI6MTcwMjc2MjI4NiwicGF0aCI6Ii8xMjM4MDg5MDkvMjkxMDE2MjEwLTQyNjM1YmYwLWM5NjgtNGQ2Zi1hOTk3LTU3ZjM3ODJlNDM0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQyMTMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTI5MDA1MmRhNGVkNjY5NTE1MDcxZWRiOTJlZmMzY2M4M2NjYWEwYjYzY2VmOWE2NTFmYTVlMDYxNjdmNTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jgIQH5Z7dNeDzpfQFV7Mzh38ykVC-vSs4FVoG9WiI8s)
> 
> یه سوال داشتم؟ دامینی که توی هر دوتا سرور باید توی دستورات سرویس قرار بگیره باید همون دامینی باشه که پشت پروکسی کلودفلره دیگه؟ یا دامین سرور ایران باید فرق کنه؟
> 
> سپاس

درود
خطایی که دریافت میکنید بخاطر اینه که به درستی تنطیمات انجام نشده
توی فایل سرویس ایران باید ادرس دامنه خارج که پشت کلودفلر هستش رو وارد کنید اما اگر کاربران روی سرور ایران باشن طبیعتا باید دامنه جدا داشته باشن♥

**Comment by babakazizigithub** [comment]
> > درود مهندس بنده طبق آموزش اجرا کردم .. روی سرور خارج اوکی هست ولی روی سرور ایران این ارور رو میده
> > ![Annotation 2](https://private-user-images.githubusercontent.com/123808909/291016210-42635bf0-c968-4d6f-a997-57f3782e4348.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjI1ODYsIm5iZiI6MTcwMjc2MjI4NiwicGF0aCI6Ii8xMjM4MDg5MDkvMjkxMDE2MjEwLTQyNjM1YmYwLWM5NjgtNGQ2Zi1hOTk3LTU3ZjM3ODJlNDM0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQyMTMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTI5MDA1MmRhNGVkNjY5NTE1MDcxZWRiOTJlZmMzY2M4M2NjYWEwYjYzY2VmOWE2NTFmYTVlMDYxNjdmNTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jgIQH5Z7dNeDzpfQFV7Mzh38ykVC-vSs4FVoG9WiI8s)
> > یه سوال داشتم؟ دامینی که توی هر دوتا سرور باید توی دستورات سرویس قرار بگیره باید همون دامینی باشه که پشت پروکسی کلودفلره دیگه؟ یا دامین سرور ایران باید فرق کنه؟
> > سپاس
> 
> درود و خسته نباشید خطایی که دریافت میکنید بخاطر اینه که به درستی تنطیمات انجام نشده دامین ها باید متفاوت باشن

ممنونم بابت جواب سریعتون 
پس هر دو دامین باید پشت پروکسی کلود فلرباشه - درسته؟

**Comment by Erfan-Fazeli** [comment]
> > > درود مهندس بنده طبق آموزش اجرا کردم .. روی سرور خارج اوکی هست ولی روی سرور ایران این ارور رو میده
> > > ![Annotation 2](https://private-user-images.githubusercontent.com/123808909/291016210-42635bf0-c968-4d6f-a997-57f3782e4348.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjI1ODYsIm5iZiI6MTcwMjc2MjI4NiwicGF0aCI6Ii8xMjM4MDg5MDkvMjkxMDE2MjEwLTQyNjM1YmYwLWM5NjgtNGQ2Zi1hOTk3LTU3ZjM3ODJlNDM0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQyMTMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTI5MDA1MmRhNGVkNjY5NTE1MDcxZWRiOTJlZmMzY2M4M2NjYWEwYjYzY2VmOWE2NTFmYTVlMDYxNjdmNTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jgIQH5Z7dNeDzpfQFV7Mzh38ykVC-vSs4FVoG9WiI8s)
> > > یه سوال داشتم؟ دامینی که توی هر دوتا سرور باید توی دستورات سرویس قرار بگیره باید همون دامینی باشه که پشت پروکسی کلودفلره دیگه؟ یا دامین سرور ایران باید فرق کنه؟
> > > سپاس
> > 
> > 
> > درود و خسته نباشید خطایی که دریافت میکنید بخاطر اینه که به درستی تنطیمات انجام نشده دامین ها باید متفاوت باشن
> 
> ممنونم بابت جواب سریعتون دامین سرور خارج باید پشت پروکسی کلودفلر باشه و دامین سرور ایران هم همون آی پی سرور ایران بدون پروکسی کلود فلر - درسته؟

بله درسته اگر مشکلی داشتید تلگرام پیام بدید💙
@the_erf23
